### ISSUE TITLE
Can you use named parameters to pass in a list variable somehow?

### ISSUE THREAD

**Issue by negcx** [lpil/yesql#2]
e.g.

A common pattern might be...

```
SELECT u.id, u.name FROM user u
WHERE u.id IN (1, 2, 3)
```

I would ideally be able to define this like:

```
SELECT u.id, u.name FROM user u
WHERE u.id IN :user_list
```

and then call... `select_user_name([3, 4, 5])` from Elixir.

is this possible? I find this is one of the main drawbacks of using raw sql as converting a list into parameters requires a million ?, ?, ? etc.

Thanks!

**Comment by lpil** [comment]
A good idea, but this is not yet supported.

**Comment by negcx** [comment]
@lpil Does it currently just transform the named elements into $1, $2, etc. in the Postgrex call?

**Comment by lpil** [comment]
Yup, try it out :)

**Comment by negcx** [comment]
Got it, I think Postgrex may implicitly support this by doing ANY($1), so perhaps with Yesql could try ANY(:my_name)

**Comment by lpil** [comment]
That's very cool. I didn't know you could do that.

Let me know how it goes!
